# Generated by Django 4.2.16 on 2024-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_uploadimage_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
