# Generated by Django 5.1.2 on 2024-11-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_delete_uploadimage_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=1, upload_to='blog/%y'),
            preserve_default=False,
        ),
    ]
